### ISSUE TITLE
仅使用数据网络时的小问题

### ISSUE THREAD

**Issue by Rakau** [CHIZI-0618/box4magisk#10]
RT，开启数据网络的情况下，重启设备，然后就无网络，必须再次开关数据网才有网络

**Comment by CHIZI-0618** [comment]
用的 Tun 么
  
疑似 Captive portal 的问题，~~或许仅仅需要等待即可正常哈哈~~

**Comment by Rakau** [comment]
> 用的 Tun 么
> 
> 疑似 Captive portal 的问题，~或许仅仅需要等待即可正常哈哈~

用TP，等了20分钟了。另外能进面板说明是启动了的，但是活动连接是0，网速指示也是0

**Comment by CHIZI-0618** [comment]
> 开启数据网络的情况下，重启设备，然后就无网络，必须再次开关数据网才有网络

我无法复现。想不出原因。
  
> 能进面板说明是启动了的，但是活动连接是0，网速指示也是0

活动连接是0就很奇怪

**Comment by Rakau** [comment]
反正很迷，核心换了也一样，估计是设备问题。不管了，~~说不定以后自己就好了~~

**Comment by CHIZI-0618** [comment]
> 反正很迷，核心换了也一样，估计是设备问题。不管了，~说不定以后自己就好了~

好吧~_~

> 必须再次开关数据网才有网络

你可以参考使用下面的脚本

```shell
#!/system/bin/sh

# Wait till device boot process complets
while [ "$(getprop sys.boot_completed)" != "1" ]; do
    sleep 1
done

# 禁用数据网络
svc data disable
sleep 2
# 开启数据网络
svc data enable
```

放到任意 Magisk 模块的 service.sh 或者 service.d 文件夹

**Comment by Rakau** [comment]
> > 反正很迷，核心换了也一样，估计是设备问题。不管了，~说不定以后自己就好了~
> 
> 好吧~_~
> 
> > 必须再次开关数据网才有网络
> 
> 你可以参考使用下面的脚本
> 
> ```shell
> #!/system/bin/sh
> 
> # Wait till device boot process complets
> while [ "$(getprop sys.boot_completed)" != "1" ]; do
>     sleep 1
> done
> 
> # 禁用数据网络
> svc data disable
> sleep 2
> # 开启数据网络
> svc data enable
> ```
> 
> 放到任意 Magisk 模块的 service.sh 或者 service.d 文件夹

谢E5姐
