### ISSUE TITLE
KernelSU刷入之后不启动

### ISSUE THREAD

**Issue by Rakau** [CHIZI-0618/box4magisk#11]
RT

**Comment by Rakau** [comment]
无任何日志生成

**Comment by CHIZI-0618** [comment]
终端执行以下命令
`/data/adb/ksu/service.d/box4KSU_service.sh`
测试能否启动成功

**Comment by Rakau** [comment]
/data/adb/ksu/service.d/box4KSU_service.sh inaccessible or not found

**Comment by CHIZI-0618** [comment]
> 

没有这个文件？

**Comment by CHIZI-0618** [comment]
请刷入 KernelSU_test 分支版本，可以去我频道或者 [Prerelease](https://github.com/CHIZI-0618/box4magisk/releases/tag/Prerelease) 下载

**Comment by Rakau** [comment]
> 请刷入 KernelSU_test 分支版本，可以去我频道或者 [Prerelease](https://github.com/CHIZI-0618/box4magisk/releases/tag/Prerelease) 下载

谢谢，失误没发现有分支

**Comment by Rakau** [comment]
使用上一切正常和面具版一致
