### ISSUE TITLE
黑名单有效，白名单无效

### ISSUE THREAD

**Issue by humbass** [CHIZI-0618/box4magisk#14]
[ 白名单无效 ]

```
# blacklist / whitelist / core
proxy_mode="whitelist"

# Android User:Package Name, For example:
user_packages_list=("0:com.android.chrome"  "0:com.google.android.youtube" )

```

已执行 `box.tproxy renew`， 也尝试过重启，居然只有 `youtube` 可以使用，另外 `0:com.google.android.youtube` 不管放在 哪个位置都可以.

黑名单模式是正常的，可以正确排除不需要的项目

**Comment by CHIZI-0618** [comment]
白名单应用列表建议用部分 VPN 类软件生成(比如 v2rayNg)，因为某些应用在必须白名单内或者某应用依赖某应用上网(这个说法并不严谨)
