### ISSUE TITLE
TUN模式开热点，电脑无法上网

### ISSUE THREAD

**Issue by Geniucker** [CHIZI-0618/box4magisk#15]
gvisor/tun/lwip都不能上网，用的是box4KSU，没用tproxy，纯TUN

**Comment by CHIZI-0618** [comment]
WSA？

**Comment by CHIZI-0618** [comment]
模块在 core 模式下不会进行额外操作，仅仅是启动内核，行为取决于内核配置文件。请检查你的配置文件

**Comment by Geniucker** [comment]
是一加10pro
下面是配置  
![Screenshot_2023-03-27-14-28-32-44.jpg](https://user-images.githubusercontent.com/61449208/227858575-13b083f6-9556-4473-a8c5-bc62ef612c4d.jpg)

**Comment by CHIZI-0618** [comment]
抱歉，我才看到你是手机开热点。我还以为是 [Windows Subsystem for Android](https://learn.microsoft.com/en-us/windows/android/wsa/)

**Comment by CHIZI-0618** [comment]
安卓热点不代理是 sing-tun 的原因，这个问题一直没修。

> gvisor/tun/lwip都不能上网

不建议使用 lwip，建议使用 system，如果不能使用再尝试 gvisor 或其他。

**Comment by Geniucker** [comment]
怪不得之前用clash for magisk的时候能用，lwip就是试一试Close #15Sent from Android device2023年3月27日 14:37，CHIZI-0618 ***@***.***>写道：
安卓热点不代理是 sing-tun 的原因，这个问题一直没修。

gvisor/tun/lwip都不能上网

不建议使用 lwip，建议使用 system，如果不能使用再尝试 gvisor 或其他。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023年3月27日 14:37，CHIZI-0618 ***@***.***>写道：
安卓热点不代理是 sing-tun 的原因，这个问题一直没修。

gvisor/tun/lwip都不能上网

不建议使用 lwip，建议使用 system，如果不能使用再尝试 gvisor 或其他。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023年3月27日 14:37，CHIZI-0618 ***@***.***>写道：
安卓热点不代理是 sing-tun 的原因，这个问题一直没修。

gvisor/tun/lwip都不能上网

不建议使用 lwip，建议使用 system，如果不能使用再尝试 gvisor 或其他。

**Comment by Geniucker** [comment]
> 安卓热点不代理是 sing-tun 的原因，这个问题一直没修。
> 
> > gvisor/tun/lwip都不能上网
> 
> 不建议使用 lwip，建议使用 system，如果不能使用再尝试 gvisor 或其他。
> 
> 稍等我给出 sing-tun 代理热点的解决方案
>   
> 方案如下：
> 尝试终端执行以下命令以添加 iptables 与策略路由规则
> ```shell
> tunName=tun0
> iptables -I FORWARD -o ${tunName} -j ACCEPT
> iptables -I FORWARD -i ${tunName} -j ACCEPT
> ip rule add from all iif ${tunName} lookup main suppress_prefixlength 0 pref 8000
> ip rule add lookup main pref 7000
> ```
> 不再代理时考虑删除规则，命令为
> ```shell
> tunName=tun0
> iptables -D FORWARD -o ${tunName} -j ACCEPT
> iptables -D FORWARD -i ${tunName} -j ACCEPT
> ip rule del pref 8000
> ip rule del pref 7000
> ```

不过tun不是clash内核自己实现的吗，和sing-tun有什么关系，有点不懂

**Comment by Geniucker** [comment]
原来如此
