### ISSUE TITLE
box4magisk和adguard for Android 的共存问题

### ISSUE THREAD

**Issue by a1623382** [CHIZI-0618/box4magisk#20]
使用clash内核时，能否有办法在core模式下放过adguard的uid？
目前的core模式在adguard使用vpn模式时，用socks5 或 http 代理入站的时候会出现本地回环，在adguard应用列表中排除root和Android系统均不起作用

_Originally posted by @a1623382 in https://github.com/CHIZI-0618/box4magisk/issues/3#issuecomment-1528648604_

**Comment by CHIZI-0618** [comment]
> 使用clash内核时，能否有办法在core模式下放过adguard的uid？ 目前的core模式在adguard使用vpn模式时，用socks5 或 http 代理入站的时候会出现本地回环，在adguard应用列表中排除root和Android系统均不起作用
> 

防止回环可以考虑
1. 使用 adguard  高级设置中的低级设置，绕过 box4 核心的 UID（默认为 0，但建议自定义核心启动用户为 1001 或其他应该被系统 VPN 服务绕过的 UID，此时需要 setcap 赋权，可参见 https://github.com/CHIZI-0618/box4magisk#更改启动-Box-服务的用户）
2. 使用 sing-tun（Clash.Meta 目前已使用 [sing-tun](https://github.com/SagerNet/sing-tun) ）的 override_android_vpn 功能，参见 https://sing-box.sagernet.org/configuration/inbound/tun/#auto_route 与 https://sing-box.sagernet.org/configuration/route/#override_android_vpn

**Comment by a1623382** [comment]
好的，谢谢

**Comment by a1623382** [comment]
emm，还是回环了，但还是谢谢解答
