### ISSUE TITLE
关于以太网共享无法使用tproxy

### ISSUE THREAD

**Issue by Githubsanae** [CHIZI-0618/box4magisk#24]
设备:三星s20
系统:oneui5(安卓13)
核心:sing-box
问题:想通过以太网共享(连接路由器)共享网络，尝试在aplist中添加eth+(以太网共享的网卡)，但是不起作用，路由器的网络无法走代理仍为直连模式，热点，usb和本机网络可正常通过代理。

**Comment by CHIZI-0618** [comment]
我没有看明白你说的
是该手机设备有 eth+ 以太网网卡 吗
