### ISSUE TITLE
sing-box时间不对

### ISSUE THREAD

**Issue by 12123ads** [CHIZI-0618/box4magisk#25]
手机时间是对的，命令行看时间也是对的，都是东8区，这日志里就变成这了
![Screenshot_20230706-011804_MT管理器.png](https://github.com/CHIZI-0618/box4magisk/assets/69107029/6529247d-a175-4804-8492-8885e283b9a3)
![Screenshot_20230706-011839_MT管理器.png](https://github.com/CHIZI-0618/box4magisk/assets/69107029/d11c716b-3c6d-47df-87c1-6ff4baac1a91)

**Comment by yaoyao-moe** [comment]
考虑一下把这个时间的小时+8
之后考虑一下您所在的时区（）

**Comment by 12123ads** [comment]
好吧，以为是时间对不上导致的错误来着（
这个报错有影响吗？![Screenshot_20230706-015350_MT管理器.png](https://github.com/CHIZI-0618/box4magisk/assets/69107029/ac302866-17e8-4dbe-bc3e-ba38348f84f6)
