### ISSUE TITLE
香港代理组正则 typo

### ISSUE THREAD

**Issue by eric1932** [CHIZI-0618/box4magisk#26]
box/clash/config.yaml
`  - {name: 香港, <<: *u,filter: "(?i)港|hk|hongkong|kong kong"}`
`kong kong` -> `hong kong`

今天设置手机的时候发现香港组没有得到预期的结果，看了半天发现有个 typo 🥹

**Comment by CHIZI-0618** [comment]
感谢，你可以提交一个 pr 修复它

**Comment by CHIZI-0618** [comment]
https://github.com/CHIZI-0618/box4magisk/pull/28
