### ISSUE TITLE
不能绕过由termux创建的进程

### ISSUE THREAD

**Issue by eykfnu** [CHIZI-0618/box4magisk#29]
blacklist模式下设置绕过termux，但是由termux创建的进程，比如AdGuardHome、MOSDNS，还是进入代理，请问有办法可以绕过这些进程吗？

**Comment by Adlyq** [comment]
@eykfnu 如果你是在root下运行的肯定不行。直接运行才行，不能用su切换用户

**Comment by eykfnu** [comment]
> @eykfnu 如果你是在root下运行的肯定不行。直接运行才行，不能用su切换用户

感谢答复，可以绕过普通进程，我忘记renew后需要重启进程，su进程，我试过chown root:net_admin 进程，但是不成功

**Comment by Adlyq** [comment]
@eykfnu chown是改文件所有者，不是执行者，绕过是根据执行者uid分流的
另外chown的生效对象是文件，不是进程

**Comment by Adlyq** [comment]
@eykfnu 可以考虑赋权

**Comment by eykfnu** [comment]
> @eykfnu 可以考虑赋权

感谢指导，参考源代码，授权进程予root:net_admin后，成功绕过box。

**Comment by CHIZI-0618** [comment]
> > @eykfnu 可以考虑赋权
> 
> 感谢指导，参考源代码，授权进程予root:net_admin后，成功绕过box。

尝试使用
https://github.com/CHIZI-0618/box4magisk#特定进程的透明代理

**Comment by eykfnu** [comment]
> > > @eykfnu 可以考虑赋权
> > 
> > 
> > 感谢指导，参考源代码，授权进程予root:net_admin后，成功绕过box。
> 
> 尝试使用 [https://github.com/CHIZI-0618/box4magisk#特定进程的透明代理](https://github.com/CHIZI-0618/box4magisk#%E7%89%B9%E5%AE%9A%E8%BF%9B%E7%A8%8B%E7%9A%84%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86)

原来有现成的解决方案，我还绕这么大个圈，感谢

**Comment by CHIZI-0618** [comment]
> 原来有现成的解决方案，我还绕这么大个圈，感谢

其实是今天看到 issue 后刚刚添加的，哈哈
