### ISSUE TITLE
无法拉取订阅

### ISSUE THREAD

**Issue by Mr-zgf** [CHIZI-0618/box4magisk#30]
开发者你好，我将机场提供的Clash订阅链接填在了模块内置的config.yaml里面，即 订阅链接 位置，终端服务也启动服务，但是就是没有节点出来，在cmfa上没有出现这个问题，由于没有基础，找不到原因，特来请教开发者。
![Screenshot_20230811171547_1](https://github.com/CHIZI-0618/box4magisk/assets/30373670/3810952c-5a06-435c-942f-51018f204357)
![Screenshot_20230811171323](https://github.com/CHIZI-0618/box4magisk/assets/30373670/95372f80-4c52-4d0d-80b1-19c31997852f)
![Screenshot_20230811171234](https://github.com/CHIZI-0618/box4magisk/assets/30373670/e34c2d8c-1ba5-4dac-90bb-b37bc0cfc36e)
![Screenshot_20230811171800](https://github.com/CHIZI-0618/box4magisk/assets/30373670/ffbd567b-262f-43db-8950-85cac519de09)

**Comment by Mr-zgf** [comment]
对了，这个订阅链接是经过转换的短链，机场提供的长链接也试过都是一样的结果

**Comment by CHIZI-0618** [comment]
@Mr-zgf 你的问题表现为 Clash.Meta 内核没有成功拉取订阅，可能是网络原因。
你可以下载这个订阅链接的内容放到 /data/adb/box/clash/proxy_providers/provider1.yaml 文件中再启动。

最后，我想说，你的问题更应该向相应内核项目的 issue 区反馈

**Comment by Mr-zgf** [comment]
了解了，感谢解答
