### ISSUE TITLE
[BUG] package 不存在导致 expr: Unexpected end of input 

### ISSUE THREAD

**Issue by xireiki** [CHIZI-0618/box4magisk#31]
## 需要材料
- 一个不存在的 package

## 复现过程
- 在 user_packages_list 中添加 "0:com.null.app"
- 使用 `su -c /data/adb/box4/scripts/box.service start` 启动 box4
- 终端执行 `su -c /data/adb/box4/scripts/box.tproxy enable`
- 出现 `expr: Unexpected end of input`

## 原因
在包名不存在时，`awk '{if($1=="'${package}'"){print $2}}' /data/system/packages.list` 输出为空

导致 `expr ${user} \* "100000" + $(awk '{if($1=="'${package}'"){print $2}}' /data/system/packages.list)` 被解析为 `expr ${user} \* "100000" + `

## 建议
建议使用变量保存 `awk '{if($1=="'${package}'"){print $2}}' /data/system/packages.list` 的结果，判断是否为空，为空则不执行 expr

**Comment by CHIZI-0618** [comment]
@xireiki 欢迎 pr

**Comment by xireiki** [comment]
@CHIZI-0618 那我试试？
