### ISSUE TITLE
能否再弄一种排除代理?...

### ISSUE THREAD

**Issue by getcurl** [CHIZI-0618/box4magisk#34]
可以弄一种通过包名排除代理的吗？或者给后台加一个能手动选择排除代理的应用列表...

**Comment by CHIZI-0618** [comment]
> 可以弄一种通过包名排除代理的吗？或者给后台加一个能手动选择排除代理的应用列表...

指定包名绕过代理？请阅读 README

**Comment by getcurl** [comment]
> > 可以弄一种通过包名排除代理的吗？或者给后台加一个能手动选择排除代理的应用列表...
> 
> 指定包名绕过代理？请阅读 README

proxy_mode="whitelist"
# blacklist / whitelist / core
user_packages_list=("0:org.telegram.messenger" "0:com.tencent.mm" "0:com.nexon.bluearchive" "0:bin.mt.plus" "0:bin.mt.plus.canary" "0:com.google.android.gms" "0:com.android.vending" "0:com.google.android.play.games" "0:mark.via" "0:com.valvesoftware.android.steam.community")

你看这个有问题吗？
为什么设置这个后会影响到其他未添加到白名单的应用，比如QQ加载图片(头像)慢，快手刷视频卡顿

**Comment by CHIZI-0618** [comment]
> proxy_mode="whitelist" user_packages_list=("0:org.telegram.messenger" "0:com.tencent.mm" "0:com.nexon.bluearchive" "0:bin.mt.plus" "0:bin.mt.plus.canary" "0:com.google.android.gms" "0:com.android.vending" "0:com.google.android.play.games" "0:mark.via" "0:com.valvesoftware.android.steam.community")
> 
> 你看这个有问题吗？ 为什么设置这个后会影响到其他未添加到白名单的应用，比如QQ加载图片(头像)慢，快手刷视频卡顿
  

考虑到并不是所有核心都有**嗅探**功能，且为了防止使用系统  DNS 解析得到的结果为保留地址进而影响透明代理（这可以称为 DNS 泄露），所以 Box 默认劫持所有常规 DNS 请求至核心的 DNS 服务。
  

您在使用哪个核心？是否在使用 FakeIP？FakeIP 天然与黑白名单冲突，请停止使用黑白名单或者改用核心的非 FakeIP DNS 方案。

**Comment by getcurl** [comment]
> > proxy_mode="whitelist" user_packages_list=("0:org.telegram.messenger" "0:com.tencent.mm" "0:com.nexon.bluearchive" "0:bin.mt.plus" "0:bin.mt.plus.canary" "0:com.google.android.gms" "0:com.android.vending" "0:com.google.android.play.games" "0:mark.via" "0:com.valvesoftware.android.steam.community")
> > 你看这个有问题吗？ 为什么设置这个后会影响到其他未添加到白名单的应用，比如QQ加载图片(头像)慢，快手刷视频卡顿
> 
> 考虑到并不是所有核心都有**嗅探**功能，且为了防止使用系统 DNS 解析得到的结果为保留地址进而影响透明代理（这可以称为 DNS 泄露），所以 Box 默认劫持所有常规 DNS 请求至核心的 DNS 服务。
> 
> 您在使用哪个核心？是否在使用 FakeIP？FakeIP 天然与黑白名单冲突，请停止使用黑白名单或者改用核心的非 FakeIP DNS 方案。

我用的另一个项目[Surfing](https://github.com/MoGuangYu/Surfing) 这个项目也是用的你这个，不过默认加了个Clash.Meta核心，还多了web后端，我感觉web后端不错，要不你也加个web后端？(其实是我不会配置核心啥的....)，抱歉回你这么慢，我现在才有空

**Comment by CHIZI-0618** [comment]
> 我用的另一个项目[Surfing](https://github.com/MoGuangYu/Surfing) 这个项目也是用的你这个，不过默认加了个Clash.Meta核心，还多了web后端，我感觉web后端不错，要不你也加个web后端？(其实是我不会配置核心啥的....)

就像他的 README 里所说的一样，它适合懒癌和小白，这并不是此项目的目标。他并没有为本项目做出实质性更改。如果不会配置本项目，那就用他的项目吧，这是  GPL-3.0 license 所允许的。

您的讨论已经超出本 issue 主题，请开新 issue 讨论您想要了解的其他主题。
