### ISSUE TITLE
把核心改名成mihomo后，DNS出现BUG

### ISSUE THREAD

**Issue by Rakau** [CHIZI-0618/box4magisk#40]
原来使用的也是mihomo核心，box没更新之前我一直用的clash的名字。看到更新后我就转移到mihomo的文件夹和名字了。核心配置文件啥都没变，直接粘贴过去的。然后开面板看到了所有host变ip了

**Comment by CHIZI-0618** [comment]
> 原来使用的也是mihomo核心，box没更新之前我一直用的clash的名字。看到更新后我就转移到mihomo的文件夹和名字了。核心配置文件啥都没变，直接粘贴过去的。然后开面板看到了所有host变ip了

mihomo 从 [3ec23c1](https://github.com/MetaCubeX/mihomo/commit/3ec23c1fc52bf65e5f9cd0b5b94ccdec139c8a84) 提交后支持从 tproxy 入口拦截 DNS，请注意 box 配置文件变动
https://github.com/CHIZI-0618/box4magisk/blob/f900e66ae6a7da9e4cb27088db9589ea73ee39d0/box/mihomo/config.yaml#L119-L120

**Comment by Rakau** [comment]
> > 原来使用的也是mihomo核心，box没更新之前我一直用的clash的名字。看到更新后我就转移到mihomo的文件夹和名字了。核心配置文件啥都没变，直接粘贴过去的。然后开面板看到了所有host变ip了
> 
> mihomo 从 [3ec23c1](https://github.com/MetaCubeX/mihomo/commit/3ec23c1fc52bf65e5f9cd0b5b94ccdec139c8a84) 提交后支持从 tproxy 入口拦截 DNS，请注意 box 配置文件变动
> 
> https://github.com/CHIZI-0618/box4magisk/blob/f900e66ae6a7da9e4cb27088db9589ea73ee39d0/box/mihomo/config.yaml#L119-L120

按照此方法，问题依旧。不过我用TUN模式就是正常的

**Comment by CHIZI-0618** [comment]
无法复现

**Comment by Rakau** [comment]
> 无法复现

已经修复，某个WIFI网络导致的问题，还有一些DNS缓存问题。配置好后重启手机就正常了
