### ISSUE TITLE
box启动失败，找不到原因

### ISSUE THREAD

**Issue by railgun100** [CHIZI-0618/box4magisk#47]
[run.log](https://github.com/CHIZI-0618/box4magisk/files/15455738/run.log)
![Screenshot_2024-05-27-20-15-40-70_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/CHIZI-0618/box4magisk/assets/98539566/16b82a68-206c-449e-b9d1-800da812cbc1)

**Comment by railgun100** [comment]
> 手动执行 `/data/adb/box/bin/mihomo -d /data/adb/box/mihomo -c config.yaml` 就能看见问题了

![Screenshot_2024-05-27-20-29-00-39_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/CHIZI-0618/box4magisk/assets/98539566/51d2f3e7-07d6-45b3-9a0a-9f636cb395b7)
没有看懂

**Comment by xireiki** [comment]
> > 手动执行 `/data/adb/box/bin/mihomo -d /data/adb/box/mihomo -c config.yaml` 就能看见问题了
> 
> ![Screenshot_2024-05-27-20-29-00-39_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/98539566/334101256-51d2f3e7-07d6-45b3-9a0a-9f636cb395b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTQ1NTQsIm5iZiI6MTcxNjgxNDI1NCwicGF0aCI6Ii85ODUzOTU2Ni8zMzQxMDEyNTYtNTFkMmYzZTctMDdkNi00NWIzLTlhMGEtOWY2MzZjYjM5NWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEyNTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMDFiYTQxM2Q1Y2JhNmVkNzAwNGQzNmU0ODkxYTBiNjIzMWU1MDk5MDFiZWMxY2Y0MDM5MTdhNTcwYmM1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RRhGwIjqaa_adUtsFbNS1tzcy4O8V0MDj8yxCvbFugc) 没有看懂

虽然我把 `-f` 打错了，打成了 `-c`，但是你连命令行都不会用，请转其他模块
