### ISSUE TITLE
使用mihomo时配置hysteria2节点无法连通

### ISSUE THREAD

**Issue by mattt-s** [CHIZI-0618/box4magisk#48]
配置格式都正确，其他vmess节点都没问题，hysteria2节点无法连通，run日志也没有任何报错，试了下Surfing就可以连通，我看了我下载的mihomo内核和Surfing 6.8.4使用的clashmeta内核一样。不知道是哪里的问题，感觉可能是box.service配置导致的

**Comment by CHIZI-0618** [comment]
看起来没有任何有用的信息。
