### ISSUE TITLE
关于FCM直连，求助🫸🫷

### ISSUE THREAD

**Issue by Elegy17** [CHIZI-0618/box4magisk#50]
FCM要怎么弄才可以直连啊？
我现在打开代理FCM就会断连，
我在hosts中放了FCM的直连ipv6地址，
不代理的情况下会直接走ipv6直连，
但是我每次打开和关闭代理FCM都会断开，
并且打开代理的情况下会直接分配ipv4有时候才是ipv6,

我该怎么弄才能在打开和关闭代理的情况下让FCM一直走本地ipv6网络而不断开连接呢？

分类规则我也去了解了一下，也写了一套分流规则，但是不管用，我不知道是不是写错了，求大佬指点一下！！！

![Screenshot_2024-06-12-20-02-22-25_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/CHIZI-0618/box4magisk/assets/24751111/0480ae83-fa42-4cb5-ad3d-00e7edd8ffe9)

![Screenshot_2024-06-12-20-02-54-24_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/CHIZI-0618/box4magisk/assets/24751111/4323b3d1-1458-4cdd-84bb-8938aa81cc53)

![Screenshot_2024-06-12-20-03-18-23_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/CHIZI-0618/box4magisk/assets/24751111/4183fd66-af09-450d-b84c-3ae73b0c88d2)

**Comment by Elegy17** [comment]
策略组的behavior写错了，不过还是不管用，断开代理Fcm还是会跟着断连🥲

**Comment by CHIZI-0618** [comment]
你所说的断开代理我理解为 `停止 Box`，这自然会打断所有连接

**Comment by Elegy17** [comment]
> 你所说的断开代理我理解为 `停止 Box`，这自然会打断所有连接

有办法让fcm连接不到box吗

**Comment by CHIZI-0618** [comment]
> > 你所说的断开代理我理解为 `停止 Box`，这自然会打断所有连接
> 
> 有办法让fcm连接不到box吗

获取 fcm 所有 ip，写入 box.config 里的 intranet 数组中，并且 clash/sing-box 核心关闭使用 fake-ip

**Comment by Elegy17** [comment]
> > > 你所说的断开代理我理解为 `停止 Box`，这自然会打断所有连接
> > 
> > 有办法让fcm连接不到box吗
> 
> 获取 fcm 所有 ip，写入 box.config 里的 intranet 数组中，并且 clash/sing-box 核心关闭使用 fake-ip

好的

**Comment by xaotag** [comment]
用dae作为上游应该也可以，也更灵活
