### ISSUE TITLE
dl.google.com下载链接无法打开

### ISSUE THREAD

**Issue by tempso** [CHIZI-0618/box4magisk#51]
由于需要下载手机刷机包，发现下载链接无法打开：
https://dl.google.com/dl/android/aosp/cheetah-ap2a.240605.024-factory-c6156301.zip

页面报错信息如下：
We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
See [Google Help](https://support.google.com/websearch/answer/86640) for more information.

已尝试关闭wifi，直接使用移动网络，出现同样的报错。
mihomo核心，配置文件使用默认，仅增加了订阅链接。

**Comment by CHIZI-0618** [comment]
建议查看 mihomo 文档，了解 dns 与路由 规则
