### ISSUE TITLE
关于小米通讯共享问题

### ISSUE THREAD

**Issue by zhengdianqian** [CHIZI-0618/box4magisk#54]
小米通讯共享貌似走的是p2p数据，如果开了box4，那么平板dns有错误，只能用于qq，微信，淘宝，部分软件无法加载图片，大部分软件无网络，如果不开就是正常的网络，这个问题有办法搞定吗，用的mihomo内核。

**Comment by CHIZI-0618** [comment]
> 小米通讯共享貌似走的是p2p数据，如果开了box4，那么平板dns有错误，只能用于qq，微信，淘宝，部分软件无法加载图片，大部分软件无网络，如果不开就是正常的网络，这个问题有办法搞定吗，用的mihomo内核。

没用过小米通讯共享，看你描述不是热点

你说 dns 错误，这是什么意思？

**Comment by zhengdianqian** [comment]
小米通讯共享:平板（没卡）数据流量会直接调用手机的数据流量或者手机的WiFi网络（在手机有WiFi的情况下）
如果手机没有启动box4的情况下，平板直接调用共享网络，网络等同于当时的手机网络，比如我手机目前是连接有软路由的WiFi那么平板一样可以访问手机能访问的网页。网络通讯正常；数据流量同理。
如果手机启动了box4的情况下，平板直接调用共享网络，无论是WiFi还是数据，哪种情况，平板只能使用qq， 微信，等小部分软件，且网页无法打开，大部分软件无网络连接（这种情况放在电脑上基本上都是DNS问题）
但是平板无法手动修改DNS因为非热点的情况，数据流量是打开就用，且小米没有这方面的设置。
目前我知道的解决办法就是手机打开热点，平板不需要连接热点，只需要手机打开！你会发现手机连接热点数是0，但是又有平板的数据在跳，并且热点不会因为长时间未连接而自动关闭。此时平板网络会正常！
我提问只是有所疑问，作者不用太当回事。

**Comment by CHIZI-0618** [comment]
> 如果手机启动了box4的情况下，平板直接调用共享网络，无论是WiFi还是数据，哪种情况，平板只能使用qq， 微信，等小部分软件，且网页无法打开，大部分软件无网络连接（这种情况放在电脑上基本上都是DNS问题） 

你说的对，应该是 DNS 问题。你提到的软件有自己的 doh，可以 ip 连接，看起来是 box4 机器没有拦截到 dns。

> 目前我知道的解决办法就是手机打开热点，平板不需要连接热点，只需要手机打开！你会发现手机连接热点数是0，但是又有平板的数据在跳，并且热点不会因为长时间未连接而自动关闭。此时平板网络会正常！ 


你说的这个很有意思，或许你可以不用打开热点，仅仅在 box4 机器上执行
`echo 1 > /proc/sys/net/ipv4/ip_forward` 
试试网络正常否

**Comment by zhengdianqian** [comment]
我开启了ip转发
cat /proc/sys/net/ipv4/ip_forward
得到的值是1，但是网络依旧无法正常![IMG_20240717_012744.jpg](https://github.com/user-attachments/assets/910a0324-a939-4ef3-8ba9-b44e7e2e4062)

**Comment by zhengdianqian** [comment]
我确认开启了ip转发
cat /proc/sys/net/ipv4/ip_forward得到的值是1
但是依旧不行！![Screenshot_2024-07-17-01-29-33-647_com.miui.gallery.jpg](https://github.com/user-attachments/assets/b298a209-cfd2-4c1d-91e2-8b4233d8ec24)

**Comment by CHIZI-0618** [comment]
有些奇怪
