### ISSUE TITLE
Apatch 环境下 TPROXY 模式局域网地址无法访问

### ISSUE THREAD

**Issue by xndeye** [CHIZI-0618/box4magisk#56]
- 使用的版本：v4.9
- 使用的核心：mihomo 1.18.6
- 问题描述：在 TPROXY 模式下，box 运行时局域网地址无法打开，可以 ping 通，互联网访问正常，mihomo 和 box 运行日志中没有发现异常；切换为 MIXED 则表现正常

**Comment by KisThFir** [comment]
我这里正常，你看看是不是路由器的luci挂了

**Comment by CHIZI-0618** [comment]
无法复现
