### ISSUE TITLE
如何使mihomo包名规则生效

### ISSUE THREAD

**Issue by Yuaaaaaan** [CHIZI-0618/box4magisk#58]
在mihomo配置文件中，使用了包名规则（PROCESS-NAME），但是一直未生效。在meta面板的连接页面检查，发现无法获取app包名
![Screenshot_2024-07-18-22-55-08-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a94edf82-64cd-4219-b3e5-3ddc6cf77251)
mihomo配置使用的v4.9版本默认配置

**Comment by csjoyxy** [comment]
tcp-concurrent: true
enable-process: true
find-process-mode: strict
global-client-fingerprint: chrome

添加进去即可。

**Comment by Yuaaaaaan** [comment]
> tcp-concurrent: true enable-process: true find-process-mode: strict global-client-fingerprint: chrome
> 
> 添加进去即可。

已经添加过了，仍然无法获取进程名

**Comment by CHIZI-0618** [comment]
> 在mihomo配置文件中，使用了包名规则（PROCESS-NAME），但是一直未生效。在meta面板的连接页面检查，发现无法获取app包名 mihomo配置使用的v4.9版本配置默认

正常情况为，使用了进程类规则，就会开启进程嗅探，除非强制关闭了 `find-process-mode: off`，强制开启进程嗅探则 `find-process-mode: always`

**Comment by horrzs** [comment]
我这边遇到的情况是 能看到第三方app的进程，但是看不到系统应用的进程，我用的系统是小米澎湃os，应用商店打开后看到的进程在控制面板内显示未 - 
![f3259344ceaecf2ea7be7dd279067be6](https://github.com/user-attachments/assets/c5c694c1-fe95-4068-8ce1-6753c41382b0)

**Comment by horrzs** [comment]
> > tcp-concurrent: true enable-process: true find-process-mode: strict global-client-fingerprint: chrome
> > 添加进去即可。
> 
> 已经添加过了，仍然无法获取进程名

请问您解决该问题了吗？

**Comment by csjoyxy** [comment]
> 我这边遇到的情况是 能看到第三方app的进程，但是看不到系统应用的进程，我用的系统是小米澎湃os，应用商店打开后看到的进程在控制面板内显示未 - ![f3259344ceaecf2ea7be7dd279067be6](https://private-user-images.githubusercontent.com/161914629/360806927-c5c694c1-fe95-4068-8ce1-6753c41382b0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NzU1NTIsIm5iZiI6MTcyNDQ3NTI1MiwicGF0aCI6Ii8xNjE5MTQ2MjkvMzYwODA2OTI3LWM1YzY5NGMxLWZlOTUtNDA2OC04Y2UxLTY3NTNjNDEzODJiMC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjRUMDQ1NDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAwNWNmZmYzN2E3ODdjNTczZGNiZTQyMTUzNWQ4Nzc5NWE4OTEyYmY5NzczYTM0NzBiNzRmMThjMGE4NjUwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s5623xzzAHzz8TTKU_aNSareGMYxOEKB0graTnexurQ)

这个问题好像无解，好像是权限的问题。之前我也是依赖于包名去做分流，发现用模块很多进程显示不全，神秘作者说无解，如果用APP走VPN的话是没问题的。通过核心的话有些第三方应用进程都不显示。
