### ISSUE TITLE
proxy_mode的值为core时mihomo的连接面板中TCP连接为Redir...

### ISSUE THREAD

**Issue by xiandu999-yu** [CHIZI-0618/box4magisk#61]
因为透明代理老蹦出端口为53的DNS查询，很明显DNS没有被劫持，所以换TUN结果就这样了...关了嗅探TCP全员纯IP...

**Comment by xiandu999-yu** [comment]
靠是auto-redirect这个参数啊...

**Comment by CHIZI-0618** [comment]
> 因为透明代理老蹦出端口为53的DNS查询，很明显DNS没有被劫持，所以换TUN结果就这样了...关了嗅探TCP全员纯IP...

因为 mihomo 提供了透明代理 TProxy 中新的 dns 拦截方式，所以我才将它从 clash 中独立，在连接情况中发现 dns 连接情况是合理的，证明 dns 拦截正常

**Comment by xiandu999-yu** [comment]
> > 因为透明代理老蹦出端口为53的DNS查询，很明显DNS没有被劫持，所以换TUN结果就这样了...关了嗅探TCP全员纯IP...
> 
> 因为 mihomo 提供了透明代理 TProxy 中新的 dns 拦截方式，所以我才将它从 clash 中独立，在连接情况中发现 dns 连接情况是合理的，证明 dns 拦截正常

因为我用的是软路由，所以配置是全部转接给软路由，当初一直纳闷咋用不了，然后看到了40+的dns请求。。。

**Comment by xiandu999-yu** [comment]
> > 因为透明代理老蹦出端口为53的DNS查询，很明显DNS没有被劫持，所以换TUN结果就这样了...关了嗅探TCP全员纯IP...
> 
> 因为 mihomo 提供了透明代理 TProxy 中新的 dns 拦截方式，所以我才将它从 clash 中独立，在连接情况中发现 dns 连接情况是合理的，证明 dns 拦截正常

DNS劫持还是要开的，域名嗅探的还原能力有限并不能100％还原有域名的IP；我把box.tproxy里的clash替换成mihomo后就开始显示域名了[在显示域名上跟我在软路由上的情况一模一样]...
