### ISSUE TITLE
VoWiFi 无法使用

### ISSUE THREAD

**Issue by Yuaaaaaan** [CHIZI-0618/box4magisk#62]
模块使用TPROXY，内核为mihomo，mihomo配置是模块内置配置。
原本希望对VoWiFi服务器进行代理，结果发现box开始运行后，VoWiFi完全无法连接，clash连接记录中也没有相关连接记录。clash即使打开全局直连，VoWiFi依旧无法连接。
哪位大神可以帮忙分析下，谢谢😺

**Comment by xiaomou1111** [comment]
额有解决方法吗
