### ISSUE TITLE
how to disable create log in mihomo folder

### ISSUE THREAD

**Issue by long-crypto** [CHIZI-0618/box4magisk#67]
when restart system or module mihomo create log in its folder with different file name. it is annoying.

**Comment by CHIZI-0618** [comment]
> when restart system or module mihomo create log in its folder with different file name. it is annoying.

You can try changing 
https://github.com/CHIZI-0618/box4magisk/blob/b003b4943f31193dfb9f095431166e67174598e3/box/scripts/box.service#L86
to
```shell
        nohup busybox setuidgid ${box_user_group} ${bin_path} -d ${box_path}/${bin_name} > /dev/null 2> ${run_path}/error_${bin_name}.log &
```


Also, in general, the Box service deletes logs from three days ago when it starts up
