### ISSUE TITLE
貌似遇到DNS的问题，不知道如何解决

### ISSUE THREAD

**Issue by Rakau** [CHIZI-0618/box4magisk#73]
获取订阅地址时出现如下提示

time="2024-09-17T10:55:26.325906848+08:00" level=warning msg="[TCP] dial 🐟 漏网之鱼 (match Match/) mihomo --> 订阅地址域名:443 error: dns resolve failed: couldn't find ip"
time="2024-09-17T10:55:26.32634164+08:00" level=error msg="initial proxy provider 订阅1 error: Get \"https://订阅地址域名/路径": EOF"

**box.config**

bin_name="mihomo"
redir_port="65533"
tproxy_port="65534"
clash_dns_port="65535"
clash_dns_listen="0.0.0.0:${clash_dns_port}"
mihome_dns_forward="true"
fake_ip_range_v4="198.18.0.0/15"
fake_ip_range_v6="fc00::/18"
tun_device="utun114514"
box_user_group="root:net_admin"
bin_name_list=("sing-box" "clash" "mihomo" "xray" "v2ray" "hysteria")
box_path="/data/adb/box"
bin_path="${box_path}/bin/${bin_name}"
run_path="${box_path}/run"
pid_file="${run_path}/${bin_name}.pid"
intranet=(0.0.0.0/8 10.0.0.0/8 100.0.0.0/8 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 192.168.0.0/16 198.51.100.0/24 203.0.113.0/24 224.0.0.0/4 240.0.0.0/4 255.255.255.255/32)
intranet6=(::/128 ::1/128 ::ffff:0:0/96 100::/64 64:ff9b::/96 2001::/32 2001:10::/28 2001:20::/28 2001:db8::/32 2002::/16 fe80::/10 ff00::/8)
ipv6="enable"
proxy_method="TPROXY"
proxy_mode="blacklist"
user_packages_list=()
gid_list=()
ap_list=("wlan+" "ap+" "rndis+" "ncm+")
ignore_out_list=()

**config.yaml**

tproxy-port: 65534
bind-address: "*"
mode: rule
allow-lan: true
log-level: info
unified-delay: true
ipv6: true
tcp-concurrent: true
global-client-fingerprint: random
geo-auto-update: true
geo-update-interval: 168
global-ua: mihomo
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
geox-url:
  geoip: "https://cdn.jsdmirror.com/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdmirror.com/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdmirror.com/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://cdn.jsdmirror.com/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb"
profile:
  store-fake-ip: true
  store-selected: true  
tun:
    enable: false
    stack: mixed
    dns-hijack:
        - any:53
        - "tcp://any:53"    
    auto-route: true
    auto-redirect: true
    auto-detect-interface: true
    device: utun114514
dns:
  enable: true
  respect-rules: true  
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true  
  ipv6: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:65535
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter: 
     - '+.lan'
     - '+.local'
     - '+.localhost'
     - '+.msftncsi.com'
     - msftncsi.com
     - msftconnecttest.com
     - '+.msftconnecttest.com'
     - '+.io.mi.com'
     - connect.rom.miui.com
     - lens.l.google.com
     - '+.stun.*.*'
     - '+.stun.*.*.*'
     - '+.stun.*.*.*.*.*'
     - '+.stun.*.*.*.*.*'
     - '*.mcdn.bilivideo.cn'
     - '+.srv.nintendo.net'
     - 'xbox.*.microsoft.com'
     - xnotify.xboxlive.com
     - localhost.ptlogin2.qq.com
     - localhost.sec.qq.com
     - tw.login.maplestory.beanfun.com
  nameserver:
     - https://120.53.53.53/dns-query
     - https://223.5.5.5/dns-query
     - https://doh.360.cn/dns-query
  proxy-server-nameserver:
     - https://doh.apad.pro/dns-query
     - https://public.dns.iij.jp/dns-query
     - https://dns.google/dns-query
  nameserver-policy:
    "geosite:cn,private":
     - https://120.53.53.53/dns-query
     - https://223.5.5.5/dns-query
     - https://doh.360.cn/dns-query
    "geosite:geolocation-!cn":
     - https://doh.apad.pro/dns-query
     - https://public.dns.iij.jp/dns-query
     - https://dns.google/dns-query
  fallback: 
     - https://doh.apad.pro/dns-query
     - https://public.dns.iij.jp/dns-query
     - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/7

proxies:

rule-providers:

  ad:
    type: http
    behavior: domain
    url: "https://cdn.jsdmirror.com/gh/privacy-protection-tools/anti-AD@master/anti-ad-clash.yaml"
    path: ./ruleset/reject.yaml
    interval: 10800

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdmirror.com/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 36000

 
proxy-providers:
    订阅1: &sub1
        type: http
        url: "订阅地址"
        path: ./providers/订阅1.yaml
        interval: 86400
        health-check:
          enable: true
          url: http://cp.cloudflare.com
          interval: 180
          tolerance: 200

proxy-groups:
  - name: 💤 自动选择（故障切换）
    type: fallback
    url: http://cp.cloudflare.com/
    interval: 180
    tolerance: 200    
    use: [订阅1]
  - name: ♻️ 自动选择（最优延迟）
    type: url-test
    url: http://cp.cloudflare.com/
    interval: 300
    tolerance: 50
    use: [订阅1]
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - REJECT
    use: [订阅1]
  - name: 🚫 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
    use: [订阅1]
  - name: 🐟 漏网之鱼
    type: select
    proxies: ["💤 自动选择（故障切换）","🎯 全球直连","♻️ 自动选择（最优延迟）"]
    use: [订阅1]

rules:
 - GEOIP,LAN,DIRECT,no-resolve
 - GEOIP,PRIVATE,DIRECT,no-resolve
 - RULE-SET,ad,🚫 全球拦截
 - RULE-SET,applications,DIRECT 
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼

**Comment by CHIZI-0618** [comment]
自己看文档https://github.com/MetaCubeX/mihomo/blob/fb4d3c41c81c378d7b1c680bf4941cccf9f77ffa/docs/config.yaml#L906 指定下载 Provider 时所使用的出站，且配置 nameserver-policy 指定订阅域名的解析 DNS 不要过代理。
