### ISSUE TITLE
5.0和5.1版本分流规则可能有错误

### ISSUE THREAD

**Issue by guhfvbj** [CHIZI-0618/box4magisk#78]
问题描述：
运行环境：Redmi k50Pro，Magisk delta，mihomo。除订阅链接外未修改config内容。

第一次刷入4.9版本，运行正常。并未卸载4.9版本box情况下，刷入5.1版本运行正常，但config.yaml并未修改。

> **彻底删除4.9版本，刷入5.0/5.1版本，执行run.sh未报错，但无法连接。所有流量全被分流至“其他[DNS_Hijack]”。重新刷机后再次使用5.1版本问题复现**

附：mihomo.log：time="2024-09-26T00:20:16.62168404+08:00"
level=info msg-"[TCP] 10.38.25.184:56960(org.
telegram.messenger, uid=10523)-->
91.108.56.111:5222 match Match using 其
他[DNS_Hijack]"
time="2024-09-26T00:20:16.630897886+08:00"
Slevel=info msg-"[TCP] 10.38.25.184:33044(org.
telegram.messenger, uid=10523) -->
91.108.56.125:5222 match Match using其
他[DNS_Hijack]"
time="2024-09-26T00:20:16.640226886+08:00"
level=info msg-"[TCP] 10.38.25.184:46218(org.
telegram.messenger, uid=10523)-->
91.108.56.125:443 match Match using 其
他[DNS_Hijack]"
time="2024-09-26T00:20:16.652087501+08:00"
level=info msg-"[TCP] 10.38.25.184:46224(org.
telegram.messenger, uid=10523)-->
91.108.56.125:443 match Match using其
他[DNS_Hijack]"
time="2024-09-26T00:20:16.66048804+08:00"
level=info msg-"[TCP] 10.38.25.184:46234(org.
telegram.messenger, uid=10523）-->
91.108.56.125:443 match Match using 其
他[DNS_Hijack]"
time="2024-09-26T00:20:17.289183425+08:00"
level=info msg-"[TCP] 10.38.25.184:54074(org.
telegram.messenger, uid=10523）-->2
149.154.167.222:443 match Match using其
他[DNS_Hijack]"
time="2024-09-26T00:20:17.737563809+08:00"
<level=info msg="[TCP] 10.38.25.184:54568(com.
android.vending, uid=10116)-->.
142.251.42.238:443 match Match using 其
他[DNS_Hijack]"
time="2024-09-26T00:20:17.979328348+08:00"
slevel=info msg="[TCP] 10.38.25.184:54584(com.
android.vending, uid=10116)-->
142.251.42.238:443 match Match using 其
他[DNS_Hijack]"

run文件夹下error_mihomo.log：
iptables: Chain already exists
iptables: Chain already exists

**Comment by CHIZI-0618** [comment]
DNS_Hijack 不要选择

_盲猜_ cache.db 清空了，所以默认选择了 DNS_Hijack_

或者使用 mihome_dns_forward true
