### ISSUE TITLE
[问题] box5.1 run_error.log

### ISSUE THREAD

**Issue by wyr121** [CHIZI-0618/box4magisk#83]
run_error.log
/data/adb/box/scripts/box.service[307]: can't create /proc/sys/net/ipv4/ip_forward: Read-only file system
/data/adb/box/scripts/box.service[307]: can't create /proc/sys/net/ipv4/conf/default/rp_filter: Read-only file system
/data/adb/box/scripts/box.service[307]: can't create /proc/sys/net/ipv4/conf/all/rp_filter: Read-only file system
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
iptables: Chain already exists.
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/all/accept_ra: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/wlan0/accept_ra: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/all/disable_ipv6: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/default/disable_ipv6: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/wlan0/disable_ipv6: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/all/accept_ra: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/wlan0/accept_ra: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/all/disable_ipv6: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/default/disable_ipv6: Read-only file system
/data/adb/box/scripts/box.tproxy[572]: can't create /proc/sys/net/ipv6/conf/wlan0/disable_ipv6: Read-only file system

**Comment by CHIZI-0618** [comment]
不影响使用
