### ISSUE TITLE
redir-host下webrtc泄漏

### ISSUE THREAD

**Issue by NiuHK** [CHIZI-0618/box4magisk#86]
采用redir-host情况下，在web面板日志下确认stun.l.google.com已经走代理了，其他的所有连接也没有走direct的，但是仍然能在webrtc查到真实ip。。。为了透明代理没法用fakeip，有办法解决吗？

**Comment by CHIZI-0618** [comment]
规则的问题，fakeip 与透明代理不冲突，并且也不能解决你说的问题。

**Comment by NiuHK** [comment]
> 规则的问题，fakeip 与透明代理不冲突，并且也不能解决你说的问题。

就是说box.config指定黑白名单，mihomo中指定fakeip是有效的吗
