### ISSUE TITLE
放进黑名单里的应用全部没有网络

### ISSUE THREAD

**Issue by 1045925330** [CHIZI-0618/box4magisk#9]
![Screenshot_20230219005148](https://user-images.githubusercontent.com/30003970/219878290-db0e896a-1a53-4148-be34-ac53676b2492.jpg)
![Screenshot_20230219005256](https://user-images.githubusercontent.com/30003970/219878295-358fadec-77ec-45a5-907a-d0a427a97d7d.jpg)

**Comment by CHIZI-0618** [comment]
是 clash fakeip 吗

**Comment by 1045925330** [comment]
原来是fakeip的问题吗，谢谢解答
