### ISSUE TITLE
启动代理后如何根据自己需要切换具体的节点，没有web界面吗？

### ISSUE THREAD

**Issue by lacanzizek** [CHIZI-0618/box4magisk#91]

**Comment by xireiki** [comment]
有，但这是核心的功能，根据你的配置而定

**Comment by lacanzizek** [comment]
我在开启代理后直接无法使用网络，但在boxformagisk上用相同配置就能上网，并且也会自动下载dashboard.
配置是https://gist.githubusercontent.com/liuran001/5ca84f7def53c70b554d3f765ff86a33/raw/a89ac358d4d1d61af38430a81b834e2bdeb5736d/config.yaml
