### ISSUE TITLE
使用mihomo内核？开启就断网？？还有无法使用wifi

### ISSUE THREAD

**Issue by Maplestoryx** [CHIZI-0618/box4magisk#92]
终端看了下ifconfig，热点接口为wlan2，没改过box.config     以下为设置   
ap_list=("wlan+" "ap+" "rndis+" "ncm+")
ignore_out_list=()
问题是：为什么接入热点的设备无网络，直接断网了？共享热点的设备都可以正常使用,连接wifi无法使用

**Comment by Maplestoryx** [comment]
自己更换了ymal文件，把这两个端口弄没了
redir-port: 7891
tproxy-port: 1536
加上去就好了，谢谢作者弄得这么好的东西🤩🥳🥳

**Comment by IMFsy** [comment]
为啥我配置文件写了这俩端口
redir-port: 7891
tproxy-port: 1536
热点还是没有网络
